<a href="https://colab.research.google.com/github/yoosoo13/yoosoo13/blob/main/%ED%98%BC%EA%B3%B5%ED%8C%8C/%ED%98%BC%EA%B3%B5%ED%8C%8C3_%EC%9E%98%EB%AA%BB%EB%90%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 누란된 값 = 결측값 = NaN

# 데이터프레임 정보 요약 확인

In [1]:
import gdown
gdown.download('https://bit.ly/3GisL6J', 'ns_book4.csv', quiet=False)

Downloading...
From: https://bit.ly/3GisL6J
To: /content/ns_book4.csv
100%|██████████| 55.5M/55.5M [00:00<00:00, 102MB/s]

'ns_book4.csv'

In [2]:
import pandas as pd
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0.0,2021-03-19

In [3]:
# info()메서드 : 열마다 누락된 값이 없는 행 갯수(NaN이 아닌 값)가 몇 개나 있는지 확인 가능
ns_book4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384591 entries, 0 to 384590
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       384591 non-null  int64
 1   도서명      384188 non-null  object
 2   저자       384393 non-null  object
 3   출판사      379950 non-null  object
 4   발행년도     384577 non-null  object
 5   ISBN     384591 non-null  object
 6   세트 ISBN  56576 non-null   object
 7   부가기호     310386 non-null  object
 8   권        63378 non-null   object
 9   주제분류번호   364727 non-null  object
 10  도서권수     384591 non-null  int64
 11  대출건수     384591 non-null  float64
 12  등록일자     384591 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 38.1+ MB

# 누락된 값 처리하기
- 각 열의 누락된 값이 정확히 몇 개가 있는지 확인
- 누락된 값을 표시하는 방법
- 누락된 값을 다른 값으로 바꾸기

## 누락된 값 갯수 확인 : isna()메서드

In [4]:
# sum()메서드와 isna()메서드로 불리언 배열의 True개수로 비어있는 행 갯수 확인
ns_book4.isna().sum()

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN    328015
부가기호        74205
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [5]:
# 누락되지 않은 값 확인 : info()메서드, notna()메서드 중 사용하면 됨
ns_book4.notna().sum()

번호         384591
도서명        384188
저자         384393
출판사        379950
발행년도       384577
ISBN       384591
세트 ISBN     56576
부가기호       310386
권           63378
주제분류번호     364727
도서권수       384591
대출건수       384591
등록일자       384591
dtype: int64

## 누락된 값으로 표시 : None과 np.nan
- 임의로 누락된 값을 만든 후 NaN으로 표시
- 숫자, 문자열 데이터 타입에 상관없이 데이프레임 셀 값을 NaN으로 표시하려면, 넘파이의 np.nan사용하세요

### int(정수형)컬럼에 None입력해보기

In [6]:
# ns_book4 데이터프레임의 '도서권수'열에 있는 첫 번째 행의 값을 None으로 바꾼 후 '도서권수' 열에 isna()메서드 적용 → 누락된 값 확인
ns_book4.loc[0,'도서권수'] = None
ns_book4['도서권수'].isna().sum()

1

In [7]:
ns_book4['도서권수'].head()
# '도서권수' 값이 1에서 NaN와 1.0으로 바뀜(이유: 판다스가 NaN을 특별한 실수 값으로 저장하기 때문)

0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
Name: 도서권수, dtype: float64

In [8]:
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,NaN,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19

### '도서권수'열의 첫 번째 행을 원래대로 1로 바꾸기 : astype()메서드
- astype()메서드_매개변수를 {'열 이름':'데이터타입'}
  - 원래 데이터 타입 : int64(정수형)
  - NaN으로 바꿨을 때 타입 : float64(실수형)
  - 다시 정수형으로 바꾸기

In [9]:
ns_book4.loc[0,'도서권수'] = 1
ns_book4 = ns_book4.astype({'도서권수': 'int32', '대출건수':'int32'})
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

### object(문자형)컬럼에 na.nan입력해보기

In [10]:
# '부가기호'컬럼의 값에 NaN값 입력해보기(np.nan로 입력해야해~)
import numpy as np
ns_book4.loc[0,'부가기호'] = np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

## 누락된 값 바꾸기(1) : loc, fillna()메서드
- '세트 ISBN'열은 대부분 비어 있다.
  - loc메서드 : 누락된 값을 NaN이 아니라, 빈 문자열('')로 바꾸기

In [11]:
# 1. 누락된 값을 찾아 불리언 배열로 반환_열의 값들이 True, False로 변환됨
set_isbn_na_rows = ns_book4['세트 ISBN'].isna()

# 2. 누락된 값을 빈 문자열('')로 바꾸기
ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''

# 3. 누락된 값이 몇 개인지 세기
ns_book4['세트 ISBN'].isna().sum()

0

In [12]:
# fillna()메서드 : 원하는 값을 전달하면 NaN을 대체할 수 있음
# ns_book4에 있는 모든 NaN을 '없음'문자열로 바꾸기
ns_book4.fillna('없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [13]:
# 특정 열만 선택해서 NaN로 바꿀 수 있음
ns_book4['부가기호'].fillna('없음').isna().sum()

# 특정 열만 선택해서 fillna()메서드를 적용하면, 열 이름 없이 개수만 있는 판다스 시리즈 객체로 반환(=열 이름이 없이 각 행의 값들만이 출력되는 것)

0

## 누락된 값 바꾸기(2): replace()메서드
- replace()메서드는 NaN는 물론 어떤 값도 바꿀 수 있는 편리한 메서드

In [14]:
# 1. 바꾸려는 값이 하나일 때, replace(원래 값, 새로운 값)
ns_book4.replace(np.nan, '없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [15]:
# 2-1. 바꾸려는 값이 여러개 일 때, replace([원래 값1, 원래 값 2], [새로운 값1, 새로운 값2])
ns_book4.replace([np.nan, '2021'], ['없음', '21']).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,없음,없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,없음,없음,1,0,2021-03-19

In [16]:
# 2-2. 바꾸려는 값이 여러개 일 때, replace({원래 값1 : 새로운 값1, 원래 값2 : 새로운 값2})
ns_book4.replace({np.nan:'없음', '2021':'21'}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,없음,없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,없음,없음,1,0,2021-03-19

In [17]:
# 3. 열 마다 다른 값으로 바꿀 때, replace({열 이름 : 원래 값}, 새로운 값)
# 예. '부가기호'열의 NaN을 '없음'으로 바꾸기
ns_book4.replace({'부가기호':np.nan}, '없음').head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,없음,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,없음,NaN,NaN,1,0,2021-03-19

In [18]:
ns_book4.replace({'부가기호' : {np.nan:'없음'},
                  '발행년도' : {'2021':'21'}}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,NaN,NaN,1,0,2021-03-19

# 정규 표현식 = 정규식 -- replac()메서드
- 문자열 패턴을 찾아서 대체하기 위한 규칙의 모음

In [19]:
# 행100의 '발행년도'는 2018이라 안 바꼈지~ > 이런경우 꽤 많아~ > 정규표현식 사용해서 바꿔보자~
ns_book4.replace({'발행년도' : {'2021':'21'}})[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,2018,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

## 숫자 찾기 : \d
- 네 자리 연도 : \d\d\d\d
- 네 자리 연도에서 뒤에 두 자리만 하나의 그룹으로 묶을 때 : \d\d(\d\d)
- \d\d == \d{2}
- \d\d(\d\d) == \d{2}(\d{2})

In [20]:
# '발행년도' 열의 값을 정규 표현식으로 두 자리 연도로 바꾸기 -- regex매개변수 사용
ns_book4.replace({'발행년도' : {r'\d\d(\d\d)' : r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

In [21]:
ns_book4.replace({'발행년도' : {r'\d{2}(\d{2})' : r'\1'}}, regex=True)[100:105]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15
102,103,C++를 사용한 언리얼 엔진 4 개발 2/e (100여 개의 레시피를 통해 배우는 ...,존 도란.윌리엄 셰리프.스테판 화이틀 지음|조경빈,에이콘,20,9791161754659,,NaN,NaN,005.11,1,1,2021-03-15
103,104,CAPCOM 격투캐릭터 만드는 법 (스트리트 파이터 캐릭터디자인),<b>Capcom</b>,비엘북스,21,9791186573419,,NaN,NaN,657.5,1,1,2021-03-15
104,105,"30대 흙수저, 기적의 강남 입성기",<b>강남</b>흙수저|부동삶|자수성부,Tornado(토네이도),20,9791158511890,,NaN,NaN,327.87,1,1,2021-03-15

## 문자 찾기 : 마침표(.), \D
- '저자'열의 값에서 (지은이),(옮긴이)삭제

In [22]:
# '저자'열 값 확인
ns_book4['저자'].head()

0              김동훈 지음
1              김태형 지음
2              김선영 지음
3    이도 게펜 지음, 임재희 옮김
4              김성곤 지음
Name: 저자, dtype: object

In [23]:
# '저자'열에서 (지은이), (옮긴이)삭제
ns_book4.replace({'저자' : {r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)' : r'\1\2'},
                  '발행년도' : {r'\d{2}(\d{2})' : r'\1'}}, regex=True)[100:105]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드, 김진웅",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아, 안기순",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15
102,103,C++를 사용한 언리얼 엔진 4 개발 2/e (100여 개의 레시피를 통해 배우는 ...,존 도란.윌리엄 셰리프.스테판 화이틀 지음|조경빈,에이콘,20,9791161754659,,NaN,NaN,005.11,1,1,2021-03-15
103,104,CAPCOM 격투캐릭터 만드는 법 (스트리트 파이터 캐릭터디자인),<b>Capcom</b>,비엘북스,21,9791186573419,,NaN,NaN,657.5,1,1,2021-03-15
104,105,"30대 흙수저, 기적의 강남 입성기",<b>강남</b>흙수저|부동삶|자수성부,Tornado(토네이도),20,9791158511890,,NaN,NaN,327.87,1,1,2021-03-15

## 잘못된 값 바꾸기
- 남산도서관 대출 데이터에서 1988년에 출간한 어떤 도서를 찾을 수 없음 → '발행년도'가 잘못 저장된 것이 있는지 확인 필요

In [25]:
# 1. 데이터 타입 지정 -- astype()메서드로 '발행년도'를 int32로 바꾸기
ns_book4.astype({'발행년도' : 'int32'})

# '1988'이라는 연도를 변환할 수 없어 오류 발생, 숫자가 아닌 다른 문자가 '발행년도'에 있는 것으로 예상됨 → 정규 표현식으로 다른 문자가 있는 연도 확인필요

ValueError: ignored

In [26]:
# 정규 표현식으로 다른 문자가 있는 연도 확인필요 -- contains()메서드 : 시리즈나 인덱스에서 문자열 패턴을 포함하고 있는지 검사
# '발행년도'열에 '1988'이 표함된 행의 개수 세어보기
ns_book4['발행년도'].str.contains('1988').sum()

407

In [27]:
# 문자 정규표현식 : \D
# '발행년도' 열에서 숫자가 아닌 문자를 포함하는 모든 행 찾기  -- contains()메서드에서 na=True로 지정
invalid_number = ns_book4['발행년도'].str.contains('\D', na = True)


# 숫자 이외의 문자가 들어간 행의 개수 출력
print(invalid_number.sum())
ns_book4[invalid_number].head()

1777

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988.,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,단기4334[2001],9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,[2019],9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019.,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018.,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [28]:
# 1. 정규 표현식으로 연도 앞, 뒤에 있는 문자 제외
ns_book5 = ns_book4.replace({'발행년도' : '.*(\d{4}).*'}, r'\1', regex=True)
ns_book5[invalid_number].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,2001,9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,2019,9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [29]:
# 2. 숫자 이외의 문자가 들어간 행의 개수와 데이터 확인
unknown_year = ns_book5['발행년도'].str.contains('\D', na=True)
print(unknown_year.sum())
ns_book5[unknown_year].head()

67

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
30838,31616,본격 한중일 세계사 5,굽시니스트 지음,위즈덤하우스,NaN,9791190065092,,NaN,NaN,NaN,0,0,2019-05-28
39130,40141,정책금융의 현황과 발전과제,정책금융연구회,한국산업은행,NaN,9788992784108,,NaN,NaN,327.1,1,0,2019-01-22
39256,40268,서울지역 유적 발굴조사 총서 3,서울역사박물관,서울역사박물관,NaN,9791186324714,9791186324431,NaN,NaN,NaN,0,0,2019-01-22
76836,81202,흰머리 큰줄기,한호진 지음,秀文出版社,[발행년불명],9788973010769,,0,NaN,699.1,1,1,2016-11-10
150543,160436,(속) 경제학사,박장환 지음,NaN,[20--],9788994339207,,1,NaN,320.9,1,2,2012-11-19

In [30]:
# 3. 더이상 변환되지 않은 값은 NaN이거나 네 자리 숫자가 아닌 값임 > 임의로 -1값으로 바꾸고 > astype()메서드로 '발행년도'열의 데이터 타입을 정수형 int32로 변환

# -1로 임의값 변경하기
ns_book5.loc[unknown_year, '발행년도'] = '-1'

# astype()으로 '발행년도' 데이터 타입 int32로 변환
ns_book5 = ns_book5.astype({'발행년도' : 'int32'})

In [31]:
# 4. '발행년도' 열의 값 중 아주 이상하게 큰 값 찾기 ] -- gt()메서드 == '>'의 뜻과 동일
ns_book5['발행년도'].gt(4000).sum()  # 4000보다 큰 값 찾기, 현재로써 단군기원....년도라서 4000넘어가는 듯

131

In [32]:
(ns_book5['발행년도'] > 4000).sum()  # 4000보다 큰 값 찾기

131

In [33]:
# 4000년이 넘는 연도 - 2333을 빼서 서기로 바꾼 다음 > 연도가 4,000년이 넘는 도서가 있는지 확인

# 1. 4000보다 큰 값 찾기
dangun_yy_rows = ns_book5['발행년도'].gt(4000)

# 2, 찾은 값에서 2333을 빼서 서기로 바꾸기
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333

# 3. 다시 4000보다 큰 값 찾기
dangun_year = ns_book5['발행년도'].gt(4000)

print(dangun_year.sum())
ns_book5[dangun_year].head(2)

13

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
222858,234268,Modern art,[computer file],GROLIER,7611,9780717233243,,NaN,NaN,609.205,1,1,2009-05-07
270269,282852,현대 영어학=Linguistic theory in modern english,이재영,열림기획,7634,9788986705072,,1,NaN,740.1,1,6,2007-04-14

In [34]:
# 그래도 4000이 넘는 '발행년도'열의 값이 13개... > -1로 표시
ns_book5.loc[dangun_year,'발행년도'] = -1

ns_book5[dangun_year].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
222858,234268,Modern art,[computer file],GROLIER,-1,9780717233243,,NaN,NaN,609.205,1,1,2009-05-07
270269,282852,현대 영어학=Linguistic theory in modern english,이재영,열림기획,-1,9788986705072,,1,NaN,740.1,1,6,2007-04-14
352000,367380,비는 어디서 왔을까?,김순한 글,웅진닷컴,-1,9788901038117,,7,NaN,453.77,1,7,2004-10-28
366958,383152,Wines of the world,NaN,Multicom Publishing,-1,9781884014062,,NaN,NaN,573.2,1,0,1970-01-01
366959,383153,The greatest children's stories ever told,NaN,QUEUE,-1,9781564348548,,NaN,NaN,843,1,0,1970-01-01

In [35]:
# 연도가 작은 값도 확인해보자 (0보다 큰 값 & 1900보다 작은 값)
old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5[old_books]

# 여전히...잘못된 값이 있군~

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
61149,64093,"고흐 씨, 시 읽어 줄까요 :내 마음을 알아주는 시와 그림의 만남",이운진 지음,사계절,176,9788958284277,,0,NaN,811.7,1,6,2017-10-27
70566,74347,정신 병리학의 문제들,지은이: 지그문트 프로이트 ;옮긴이: 황보석,열린책들,151,9788932905181,9788932905082,9,10,185.5,1,4,2017-04-26
79550,84164,(최근 7년간) 중요 민법판례 :[2009년 1월~2016년 6월 중요 판례],이광섭 편저,법학사,163,9788962898651,,9,NaN,365,1,14,2016-09-27
147950,157759,(한·중·일) 밥상 문화 :대표음식으로 본 3국 문화비교,김경은 지음,이가서,132,9788958643012,,0,NaN,381.75,1,30,2013-02-19
194576,205407,책으로 뒤덮인 집의 비밀,N.E. 보드 지음 ;피터 퍼거슨 그림 ;김지현 옮김,개암나무,1015,9788992844413,,7,NaN,843,1,15,2010-08-18
287252,300283,(밝혀질)우리歷史,吳在城 著,黎民族史硏究會,1607,9788986892130,,0,NaN,911,1,5,2006-07-06

In [36]:
# 아직도 잘못된 값 -1로 설정하고 전체 행 개수 확인
ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum()  # eq(-1) :  -1와 같은 값이 몇 개 인지 셈

86

## 누락된 정보 채우기
- 위에서 총 86권이 연도가 잘못 저장되었거나 알 수 없음을 확인
- '발행년도'열을 비롯해 다른 열의 잘못되거나 누락된 값을 채워보기

In [37]:
# '도서명', '저자', '출판사', '발행년도'열이 분석에 중요하다고 판단
# 위 4개의 열에는 누락된 값이 있으면 안됨

# 위 4개의 열에 누락된 값 확인, '발행년도'열이 -1인 행의 개수 확인
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())
ns_book5[na_rows].head(2)

5268

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
78,79,아산 정주영 레거시,김화진,NaN,2021,9788952129529,,NaN,NaN,325,1,1,2021-03-15
265,278,골목의 시간을 그리다,정명섭.김효찬 지음,NaN,2021,9791191266054,,NaN,NaN,NaN,1,0,2021-03-12

In [38]:
# 값이 누락되었거나 알 수 없는 행이 5,268개 → 뷰피풀수프 사용해서 채워넣기
import requests
from bs4 import BeautifulSoup

In [39]:
def get_book_title(isbn):
  # Yes24 도서 검색 페이지 URL
  url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
  # URL에 ISBN을 넣어 HTML 가져오기
  r= requests.get(url.format(isbn))
  # HTML 파싱
  soup = BeautifulSoup(r.text, 'html.parser')
  # 클래스 이름이 'gd_name'인 <a> 태그의 텍스트를 가져옵니다.
  title = soup.find('a', attrs={'class' : 'gd_name'}).get_text()
  return title

In [40]:
# get_book_title()함수를 '골목의 시간을 그리다'책의 ISBN으로 테스트
get_book_title(9791191266054)

'골목의 시간을 그리다'

___

In [41]:
import re

def get_book_info(row):
  title = row['도서명']
  author = row['저자']
  pub = row['출판사']
  year = row['발행년도']

  # Yes24 도서 검색 페이지 URL
  url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

  # URL에 ISBN을 넣어 HTML을 가져옵니다.
  r = requests.get(url.format(row['ISBN']))

  # HTML파싱
  soup = BeautifulSoup(r.text, 'html.parser')

  # 1. '도서명' : 클래스 이름이 'gd_name'인 <a> 태그의 텍스트를 가져옵니다.
  try:
    if pd.isna(title):
      title = soup.find('a', attrs = {'class' : 'gd_name'}).get_text()
  except AttributeError:
    pass


  # 2. '저자명' : 클래스 이름이 'info_auth'인 <span>태그 아래 <a>태그의 텍스트를 가져옵니다.
  try:
    if pd.isna(author):
      author = soup.find('span', attrs = {'calss' : 'info_auth'}).find_all('a')  # '도서명'과 달리 '저자명'은 저자가 2명 이상 일 수 있기 때문에 뷰티풀수프의 find_all()메서드 사용 → <a>태그 여러개 추출되면 하나로 합쳐주는게 좋음
      author_list = [auth.get_text() for auth in authors]  # <a>태그에 속한 모든 텍스트를 파이썬 리스트에 저장
      author = ','.join(author_list) # 추출한 결과를 join()메서드를 사용해 하나의 문자열로 합쳐줌
  except AttributeError:
    pass


  # 3. '출판사' : 클래스 이름이 'info_pub'인 <span>태그 아래 <a>태그의 텍스트를 가져옵니다.
  try:
    if pd.isna(pub):
      pub = soup.find('span', attrs = {'class' : 'info_pub'}).find('a').get_text()
  except AttributeError:
    pass

  # 4. '발행년도' :  클래스 이름이 'info_data'인 <span>태그 아래 텍스트를 가져옵니다.
  try:
    if pd.isna(year):
      year = soup.find('span', attrs = {'class' : 'info_date'}).get_text()
      # 정규표현식으로 찾은 값 중에 첫 번째 것만 사용합니다.
      year = re.findall(r'\d{4}', year_str)[0]
  except AttributeError:
    pass

  return title, author, pub, year

In [42]:
# ns_book5 데이터프레임에서 결측치가 있는 처음 두 개의 행에 대해 get_book_info 함수를 적용하여 웹 스크래핑 결과를 얻기 위함
update_sample = ns_book5[na_rows].head(2).apply(get_book_info, axis=1, result_type='expand')
update_sample

               0           1           2     3
78    아산 정주영 레거시         김화진  서울대학교출판문화원  2021
265  골목의 시간을 그리다  정명섭.김효찬 지음      초록비책공방  2021

In [47]:
# 위 함수를 5,286개 행에 모두 적용하기엔 시간이 오래 걸림
gdown.download('https://bit.ly/3UJZiHw', 'ns_book5_update.csv', quiet=False)
ns_book5_update = pd.read_csv('ns_book5_update.csv', index_col=0)
ns_book5_update.head()

Downloading...
From: https://bit.ly/3UJZiHw
To: /content/ns_book5_update.csv
100%|██████████| 406k/406k [00:00<00:00, 70.4MB/s]

                          도서명               저자         출판사  발행년도
78                 아산 정주영 레거시              김화진  서울대학교출판문화원  2021
265               골목의 시간을 그리다       정명섭.김효찬 지음      초록비책공방  2021
354                    한국인의 맛           정명섭 지음         추수밭  2021
539              한성부, 달 밝은 밤에           김이삭 지음      고즈넉이엔티  2021
607  100일 완성 마그마 러시아어 중고급 단어장  러포자 구제 연구소 외 지음         문예림  2021

In [50]:
# ns_book5 데이터프레임을 ns_book5_update데이터프레임 데이터로 업데이트 한 후 누락된 행이 몇 개 인지 다시 확인해보기
ns_book5.update(ns_book5_update)
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())

# 누락된 값이 있는 행은 4,615개로 뷰티풀수프로 데이터를 채우기 전보다 653개 감소 > 마지막으로 누락된 값 값을 가진 행은 삭제, 분석 대상에서 제외시킴

4615

In [53]:
ns_book5['발행년도'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 384591 entries, 0 to 384590
Series name: 발행년도
Non-Null Count   Dtype
--------------   -----
384591 non-null  float64
dtypes: float64(1)
memory usage: 2.9 MB

In [57]:
# 마지막으로 누락된 값 값을 가진 행은 삭제, 분석 대상에서 제외시킴 -- dropna()메서드 사용
ns_book5 = ns_book5.astype({'발행년도' : 'int32'})

# 1. '도서명', '저자', '출판사'열을 리스트로 지정한 후, 2. 누락된 값이 있는 행을 삭제
ns_book6 = ns_book5.dropna(subset=['도서명', '저자', '출판사'])

# 3. '발행년도'열 값이 -1이 아닌 행만 선택하여 ns_book6 데이터프레임 생성
ns_book6 = ns_book6[ns_book6['발행년도'] != -1]
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,,NaN,NaN,NaN,1,0,2021-03-19

In [58]:
ns_book6.to_csv('ns_book6.csv', index=False)